server:
  port: 80
spring:
  application:
    name: los-service
datasource:
  url: ${DB_URL:jdbc:postgresql://<aurora-endpoint>:5432/appdb}
  username: ${DB_USER:admin}
  password: ${DB_PASS:changeme}
